AWSTemplateFormatVersion: 2010-09-09
Description: pf-001 template for S3

Parameters:
  Project:
    Type: String
    Default: pf-001

Resources:
# ------------------------------------------------------------#
#  Bucket
# ------------------------------------------------------------#
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${Project}-s3
# AWS リージョン
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
          BucketKeyEnabled: True